language: node_js
before_install: 
 - cd Assignment-1
addons:
  ssh_known_hosts: moon.scs.ryerson.ca
before_deploy:
 - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa
 - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet ${TRAVIS_BUILD_DIR}/ci_play adaginaw@moon.scs.ryerson.ca:/home/avm/courses/cps847/adaginaw
  on:
    branch: master
